name: Deploy Release App

on:
  push:
    branches:
      - main

env:
  gcp_project_id: ccv-website-next
  gcp_registry_url: us-central1-docker.pkg.dev
  gcp_artifact_registry: gcp-ccv-website
  image: ${{ github.event.repository.name }}-release

jobs:
  build-release-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.gcp_project_id }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
          export_environment_variables: true
          create_credentials_file: true

      - uses: "google-github-actions/setup-gcloud@v2"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build and Upload Search Index
        run: npm run search:index
        env:
          MEILISEARCH_HOST: ${{ secrets.MEILISEARCH_HOST }}
          MEILISEARCH_MASTER_KEY: ${{ secrets.MEILISEARCH_MASTER_KEY }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.gcp_registry_url }}
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker Auth
        shell: bash
        run: |
          gcloud auth configure-docker ${{ env.gcp_registry_url }}

      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ env.gcp_registry_url }}/${{ env.gcp_project_id }}/${{ env.gcp_artifact_registry }}/${{ env.image }}:latest
          build-args: |
            NEXT_PUBLIC_MEILISEARCH_HOST=${{ secrets.MEILISEARCH_HOST }}
            NEXT_PUBLIC_MEILISEARCH_SEARCH_KEY=${{ secrets.MEILISEARCH_SEARCH_KEY }}

      - uses: "google-github-actions/deploy-cloudrun@v2"
        id: "deploy"
        with:
          service: ${{ env.image }}
          project_id: ${{ env.gcp_project_id }}
          image: ${{ env.gcp_registry_url }}/${{ env.gcp_project_id }}/${{ env.gcp_artifact_registry }}/${{ env.image }}
          flags: "--allow-unauthenticated"
          env_vars: |
            NEXT_PUBLIC_MEILISEARCH_HOST=${{ secrets.MEILISEARCH_HOST }}
            NEXT_PUBLIC_MEILISEARCH_SEARCH_KEY=${{ secrets.MEILISEARCH_SEARCH_KEY }}

      - name: Show Deployment URL
        run: |
          echo "ðŸš€ Deployed to: ${{ steps.deploy.outputs.url }}"
